# Generated by Django 2.0 on 2019-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(default=7567377)),
                ('profile_pic', models.FileField(default='set.jpg', upload_to='images/')),
            ],
        ),
    ]
