# Generated by Django 2.0 on 2019-02-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='mobile',
            field=models.BigIntegerField(max_length=20),
        ),
    ]
