# Generated by Django 2.0 on 2019-02-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='designation',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='info',
            name='department',
        ),
    ]
